
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_app_development

  
 
test:
  <<: *default
  database: twitter_app_test


production:
  <<: *default
  database: twitter_app_production
  username: twitter_app
  password: <%= ENV['TWITTER_APP_DATABASE_PASSWORD'] %>
